// Curriculum for the Million Dollar Roadmap.
// Derived from Michia Rohrssen's videos:
//  - "How to Make $1,000,000 From Scratch" (3-step blueprint)  [youtu.be/y5ks4FhoGfQ]
//  - "$110M CEO Explains: 7 Skills to Make Your First $1M"     [youtu.be/gGmM-Oo4_WA]

const CURRICULUM = {
  northStar: {
    title: "Your First $1,000,000",
    subtitle: "A billion-dollar desperate market × a high-leverage business × a skill stack no one can compete with.",
  },
  phases: [
    {
      id: "p0",
      num: 0,
      title: "Get Your Money Right — The 7 Baby Steps",
      tagline: "The plan 10 million people have used to get straightened up. Your income is your most powerful wealth-building tool — free it first.",
      intro: "From Dave Ramsey's 7 Baby Steps: personal finance is 80% behavior, 20% math. Debt is the most aggressively marketed product in America (Visa, Mastercard, Discover and Amex alone spend $4B/year selling it), and 'the borrower is slave to the lender.' Run this track in parallel with the business phases — a founder with no payments makes braver decisions ('your career choices are different when you're free'). Do the steps in order; don't remix them.",
      steps: [
        {
          id: "bs1-starter",
          title: "Baby Step 1 — Save $1,000 (Starter Emergency Fund)",
          time: "under 30 days",
          lesson: [
            "Save <b>$1,000</b>, set it aside, and touch it only for true emergencies. Criticism addressed: 'adjust it for inflation!' — Ramsey's answer: it was <i>never</i> meant to be enough. It exists so a $350 alternator doesn't derail your debt payoff and kill your <b>emotional momentum</b> — this is a behavior-modification program, and momentum is the fuel.",
            "It's the easiest step (garage sale, sell stuff online, clean out the piggy bank — most people can do it inside 30 days) and simultaneously the hardest: it's the moment you decide whether you'll actually submit to a different set of ideas than the ones that got you here. That's called change, and change is uncomfortable.",
            "Don't reorder the steps or negotiate with them. 'Don't argue with the eight-pack when you've got a keg.'",
          ],
          actions: [
            "Open a separate savings account today and name it EMERGENCY ONLY.",
            "List 10 things you can sell this week (garage sale, Craigslist, marketplace). Sell them.",
            "Move every spare dollar in until the account reads $1,000.",
            "Write the rule where you'll see it: this money is for emergencies — not couches, not boats, not deals.",
          ],
          metric: "$1,000 sitting untouched in a separate account",
        },
        {
          id: "bs2-snowball",
          title: "Baby Step 2 — Kill All Debt with the Debt Snowball",
          time: "18–24 months average",
          lesson: [
            "List every debt except your house, <b>smallest balance to largest</b> (ignore interest rates). Minimum payments on everything but the smallest; attack the smallest with everything you have. When it dies, roll its payment into the next one. Squeeze, throw, repeat — by the big ones, you're shoveling huge payments.",
            "Criticism addressed: 'the avalanche (highest interest first) is mathematically correct.' Ramsey: incomplete math — a behavior tool must include <b>probability of completion</b>. The snowball completes ~80% of the time; the avalanche ~20%, saving only ~1.3 months and ~$1,500 if executed perfectly. A Northwestern University study concluded the snowball wins. Quick wins build the hope that finishes the race. 'If we were doing math, we wouldn't have credit card debt.'",
            "The myths the video dismantles: airline miles (of 10,167 millionaires studied, the number who credited credit-card points: <b>zero</b>) · 'debit cards aren't protected' (Visa's zero-liability covers debit too) · car payments as a way of life (average payment ≈ $700/month — 10 months of that buys a decent cash car) · leasing ('the most expensive way to finance a car' — effective rate ≈ 14.2%; 82% of millionaires never had a car loan or lease) · building your FICO score (an 'I-love-debt score' — 100% of it measures how you interact with debt, not whether you're winning) · cosigning ('the bank, whose whole job is lending, decided your relative won't pay') · 'you can't go to college without loans' (71% of millionaires took none).",
            "The method is <b>gazelle intensity</b> (Proverbs 6): the cheetah is faster, but the gazelle escapes 18 of 19 times because one of them is running for its life. Deliver yourself — nobody in the White House is coming to prosper your house. Sell so much stuff the kids think they're next; work extra; stop borrowing — have the 'plastectomy.' Pause investing temporarily and throw everything at the debt.",
          ],
          actions: [
            "List every non-mortgage debt smallest to largest in this step's notes — today, all of them.",
            "Cut up / freeze the credit cards. No new borrowing, period.",
            "Pause retirement contributions temporarily and redirect the money at the smallest debt.",
            "Add income: one extra job, overtime, or 10 extra sales calls a day (your Phase 1 skill compounds here).",
            "Every debt you kill, roll its payment into the next — track the snowball in your notes monthly.",
          ],
          metric: "Everything but the house: $0",
        },
        {
          id: "bs3-fund",
          title: "Baby Step 3 — Fully Funded Emergency Fund (3–6 Months)",
          time: "6–12 months",
          lesson: [
            "Stay gazelle-intense one more step: bank <b>3–6 months of expenses</b>. It's going to rain — 78% of American households have a major negative financial event in any given 10-year window. An emergency fund turns a crisis into an inconvenience; without one, life is drama-to-drama-to-drama.",
            "Criticism addressed: 'invest your emergency fund!' No. It's not an investment, it's <b>insurance</b> — you're paying (in foregone returns) to protect the things that make you money. High-yield savings, liquid, boring. Your spouse's security is worth more than the spread.",
            "When you're here — no payments but the house, $15–30k in the bank — you're in roughly the top 10% of Americans financially. Now <b>downshift from intense to intentional</b>: vacations, eating out, and investing come back, funded by all the payments you no longer have.",
          ],
          actions: [
            "Calculate your real monthly expenses; multiply by 3–6 and write down your target number.",
            "Auto-transfer to a high-yield savings account every payday until you hit it.",
            "Define 'emergency' in writing with your spouse/partner — and what it isn't.",
            "When funded: officially downshift. Restart investing and normal life, on a written budget.",
          ],
          metric: "3–6 months of expenses, liquid and untouched",
        },
        {
          id: "bs47-wealth",
          title: "Baby Steps 4–7 — Invest 15%, Kids' College, Kill the Mortgage, Give",
          time: "runs simultaneously, then for life",
          book: { name: "Baby Steps Millionaires", author: "Dave Ramsey" },
          lesson: [
            "<b>Step 4 — 15% of household income into retirement.</b> Compound interest is 'the eighth wonder of the world.' The S&P 500 has averaged ~11.2% since inception; even the dumbed-down model — $77k average income, no raise for 35 years, 10% returns — lands at $3.6M. Criticism addressed: '15% isn't enough anymore' — it isn't forever; after the house is paid (step 6→7) you invest far more. Investing = long track record, left alone a long time. Day trading (78% lose money) and crypto are speculating, not investing; millionaires' portfolios are 'disturbingly boring.'",
            "<b>Step 5 — save for kids' college</b> in an ESA/529. Pay cash; there is no good student loan (student debt is delaying marriage, moving out, and home-buying for a whole generation). College is worth it 'if you study the right things at the right place at the right price' — there's zero data linking the brand name of the school to success. Trades and certifications are legitimate routes ($110k welders, six-figure devs with no degree). Scholarships? You can withdraw the scholarship amount from the 529 penalty-free.",
            "<b>Step 6 — pay off the house early.</b> The typical millionaire in the 10,167-person study: 52 years old, paid-off house worth ~$600k plus ~$700k in retirement accounts, built over ~18 boring years. Number who got rich borrowing against the house to buy funds: zero. Criticism addressed: 'keep the mortgage for the tax deduction' — 90% of Americans take the standard deduction, and even for the rest, paying the bank $10,000 of interest to save $2,200 of tax is trading dollars for quarters. People on this plan pay the house off in ~7 years.",
            "<b>Step 7 — build wealth and give outrageously.</b> Generosity is a character quality, not an act — and generous people statistically prosper (better marriages, better promotions, better lives). 'Money is like candles: lighting someone else's doesn't diminish yours.' Live like no one else so that later you can live — and give — like no one else.",
          ],
          actions: [
            "Set retirement contributions to exactly 15% of gross household income (401k/Roth IRA, boring index/mutual funds).",
            "If you have kids: open an ESA or 529 this month and start any amount.",
            "Apply every raise and windfall to the mortgage principal; calculate your payoff date at the current pace.",
            "Build giving into the budget now — a fixed percentage, automatic, starting this month.",
            "Add a goal in the Goals tab: your net-worth-$1M date, using the millionaire math above.",
          ],
          metric: "15% investing on autopilot; a written mortgage-payoff date; giving line in the budget",
        },
      ],
    },
    {
      id: "p1",
      num: 1,
      title: "Build Your Million-Dollar Skill Stack",
      tagline: "Seven skills. 4/10 in all of them, 9/10 in one or two. That combination makes you a category of one.",
      intro: "Average people learn one or two skills. Exceptional earners combine the right skills so they multiply: 10 × 10 × 10, not 10 + 10 + 10. Get to a working baseline in all seven, then pick one or two to push to superpower level. Work through these while you execute the later phases — the skills are the foundation, not a prerequisite you wait on.",
      steps: [
        {
          id: "s1-sales",
          title: "Skill 1 — Sales & Persuasion",
          time: "1 month of daily practice",
          book: { name: "Never Split the Difference", author: "Chris Voss" },
          lesson: [
            "Everything in life is sales — winning a business deal, convincing friends where to eat, negotiating with your spouse. The specific art to master is <b>verbal sales</b>: the ability to direct and steer a live conversation toward a desired outcome in real time.",
            "A script isn't enough. Real conversations are like sparring — jab, right hook, adjust. You need to read the dynamics as they happen and keep steering. If you learn one skill first, make it this one.",
            "The single best book (out of ~50 the creator read on this topic): <b>Never Split the Difference</b> by former FBI hostage negotiator Chris Voss. It teaches you to stay calm, persuade, and win conversations in the highest-stakes environments in the world — the exact tactics he credits for closing his $110M exit.",
          ],
          actions: [
            "Order or download Never Split the Difference today.",
            "Make 50 outreach/sales calls today (any product, any pitch — reps matter more than outcome).",
            "Tonight, review the day: when did people lean in? Tune out? Get annoyed? Write 3 lessons down.",
            "Apply one Voss tactic tomorrow (mirroring, labeling, or a calibrated question).",
            "Repeat the call → review → apply loop for 30 days.",
          ],
          metric: "50 calls/day × 30 days, with a written nightly review",
        },
        {
          id: "s2-copy",
          title: "Skill 2 — Copywriting & Digital Marketing",
          time: "2–3 weeks to baseline",
          book: { name: "Copywriting Secrets", author: "Jim Edwards" },
          lesson: [
            "Copywriting is the closest thing to a superpower in an internet-powered world: if you can write good copy, you can make money. Period. It's the art of putting your sales-and-persuasion skills on paper (or into a video script).",
            "All copy runs on a three-step formula: <b>Hook → Persuade → Call to Action</b>. Hook them so they want more, persuade them toward a view (storytelling, benefits), then tell them exactly what to do next — buy, sign up, subscribe. Every ad you've ever seen runs this formula; trillions are spent on it yearly.",
            "Read <b>Copywriting Secrets</b> by Jim Edwards — straightforward, recent, and everything in it works in today's environment.",
          ],
          actions: [
            "Start a swipe file: a folder of screenshots of any ad, hook, or post that stopped your scroll. Add 3 today.",
            "For each swipe, write one sentence: WHY did this hook me?",
            "Write and post one short-form piece (tweet, TikTok/Reel, or thread) using Hook → Persuade → CTA.",
            "Post 5 more over the next week and compare which hooks performed. Double down on the winner's style.",
          ],
          metric: "20+ swipes collected, 6+ public posts tested",
        },
        {
          id: "s3-product",
          title: "Skill 3 — Product Thinking",
          time: "2–4 weeks",
          book: { name: "The Lean Startup", author: "Eric Ries" },
          lesson: [
            "To make money you must build something people want. There are two ways: be born Steve Jobs, or learn <b>product thinking</b> — the art of getting potential customers to teach you what they'll buy.",
            "You don't need great ideas. You need great questions. Guide a customer through a conversation where they spell out the problems costing them money and the solutions that would make them money. Then you already know it sells before you build it.",
            "Read <b>The Lean Startup</b> by Eric Ries — the exact framework for finding potential customers and interviewing them without forcing your product on them.",
          ],
          actions: [
            "Write your interview script: What are your top 3 problems at work/in this area? What have you tried? If you could wave a magic wand, what would the fix look like? What would that be worth?",
            "Book your first 5 customer interviews this week (friends count if you have no market yet).",
            "Complete 20 interviews total. After each one, log the problems mentioned and what a fix is worth.",
            "Rank the problems by (frequency mentioned × dollar value). The top item is your product hypothesis.",
          ],
          metric: "20 interviews logged, one ranked problem list",
        },
        {
          id: "s4-code",
          title: "Skill 4 — Basic Programming (Enough to Be Dangerous)",
          time: "1–2 weekends",
          lesson: [
            "You don't need to become a programmer. You need to <b>understand how programmers think</b> so you can hire them, partner with them, and design solutions with them — the same way Elon Musk knows batteries and rockets deeply enough to direct people who build them.",
            "The target level: writing <b>pseudo-code</b> — describing on a whiteboard exactly what a program should do (inputs, if-then logic, loops, outputs) so an engineer can build it and you can review it together.",
            "Everything in today's economy is digital. Ignoring how software works is ignoring the greatest wealth opportunity of our generation.",
          ],
          actions: [
            "Watch a 'basics of programming' tutorial on YouTube (pick one from the last 6 months).",
            "Write a Hello World program in HTML, then CSS, then JavaScript (tutorials abound — it's the classic first exercise).",
            "Learn what an if/then and a loop are, and explain them out loud to someone.",
            "Write pseudo-code for a feature of the product idea from your interviews (Phase 1, Skill 3).",
          ],
          metric: "3 Hello Worlds + 1 page of pseudo-code for your own idea",
        },
        {
          id: "s5-outbound",
          title: "Skill 5 — Cold Outbound",
          time: "ongoing system",
          book: { name: "The Sales Development Playbook", author: "Trish Bertuzzi" },
          lesson: [
            "'Build it and they will come' is a load of crap. If you rely on inbound, you're not in control of your destiny. Wealth is built systematically and predictably — which means going out and getting customers who've never heard of you: <b>cold outbound</b>, via sequences of cold calls and cold emails.",
            "Good news: you already have the ingredients. Cold emails = your copywriting. Cold calls = your sales & persuasion. Outbound is combining them into a repeatable sequence — call or email first, how many touches, when to leave voicemail. These are solved problems; copy the playbook.",
            "Read <b>The Sales Development Playbook</b> by Trish Bertuzzi — a step-by-step, plug-in outbound system.",
          ],
          actions: [
            "Define your ideal customer profile in one sentence (who, size, role, pain).",
            "Build a list of 100 named prospects (LinkedIn, directories, Google Maps — whatever fits your market).",
            "Write a 5-touch sequence: call → email → call+voicemail → email → LinkedIn message.",
            "Run 50 touches per day against the list. Track connects, conversations, and meetings booked.",
          ],
          metric: "50 touches/day; meetings booked per 100 touches",
        },
        {
          id: "s6-ai",
          title: "Skill 6 — AI Leverage",
          time: "1 week to habit",
          lesson: [
            "Ignore the hype — AI won't do your job for work that matters. But two workflows are genuine game-changers, and skipping them leaves you behind the workforce:",
            "<b>1. First drafts.</b> The hardest part of anything is starting. Have AI produce the first draft of any project — script, outline, email, plan. You might discard 99%, but humans are far better editors than first-drafters, so you move much faster.",
            "<b>2. AI as the refiner.</b> Don't take the draft away and edit alone. Tell the AI what's wrong ('too corny — give me 3 less corny versions', 'add a real statistic with a source link') and iterate. Contrast its generic take with your experience to sharpen your own thinking.",
          ],
          actions: [
            "Pick your AI tool (ChatGPT, Claude, etc.) and use it for a first draft of something real today.",
            "Practice the refine loop: give it 3 rounds of specific critique on that draft instead of editing alone.",
            "For one week, before starting ANY task, ask: 'can AI give me the first draft of this?'",
            "Watch one beginner guide for your chosen tool published in the last 2–6 months.",
          ],
          metric: "AI-first-draft habit on every project for 7 straight days",
        },
        {
          id: "s7-design",
          title: "Skill 7 — Design Fundamentals",
          time: "1–2 weeks",
          lesson: [
            "You get one or two seconds to make a first impression, and people judge books by covers. If your product, deck, or page looks like a lazy template, buyers (and investors) assume the product got the same effort — and pass.",
            "Learn the basics: <b>proportion, white space, color theory, typography</b>. Free YouTube tutorials ('fundamentals of design') are all you need.",
            "Train your eye at <b>dribbble.com</b> → Popular shots: designs upvoted by designers themselves. Compare your work against them and ask what's missing. (Later you can hire designers there too.)",
          ],
          actions: [
            "Watch a 'fundamentals of design' tutorial covering proportion, white space, color, and typography.",
            "Browse dribbble.com popular shots for 20 minutes; save 10 designs you love to your swipe file.",
            "Design 2 real assets in Canva or Photoshop (a banner ad, a YouTube banner, a landing-page mockup).",
            "Put your asset next to a dribbble shot and write down 3 concrete differences. Fix them.",
          ],
          metric: "2 assets designed, critiqued against pro work, and revised",
        },
        {
          id: "s8-stack",
          title: "Capstone — Assemble the Stack",
          time: "30 minutes of decision",
          lesson: [
            "You can't be 10/10 at all seven — you'd study forever and never build wealth. The play: get a <b>4–5/10 baseline in all seven</b> (jack of all trades foundation), then choose <b>one or two skills to push to 9–10/10</b>. Think of a city skyline: solid foundational buildings, plus one or two skyscrapers that define it.",
            "The right combination makes you uniquely suited to do things only you can do. Your earning potential is no longer 'what does a good salesperson make?' — you're a category of one, and you set the price.",
          ],
          actions: [
            "Score yourself 1–10 on each of the seven skills right now (be honest). Note it in this step's notes.",
            "Choose your 1–2 superpower skills — where your natural edge and your market's needs overlap.",
            "Write one sentence: 'My stack is X + Y + baseline everything, which makes me the only person who ___.'",
            "Set a goal in the Goals tab for reaching 9/10 in your chosen skills, with a date.",
          ],
          metric: "A named, written skill stack with a deadline",
        },
      ],
    },
    {
      id: "p2",
      num: 2,
      title: "Find Your Billion-Dollar Desperate Market",
      tagline: "Push the boulder downhill: pick a market so desperate for a solution that winning is almost automatic.",
      intro: "The creator's businesses kept failing for seven years — not because he was a bad entrepreneur, but because he picked markets where he had to create his own momentum. The fix, learned from Jeff Bezos: spot a massive disruption early (Bezos quit his hedge fund job over one data point — web usage growing 2,300%/year — and started Amazon). Get the beginning right and everything downstream gets easier.",
      steps: [
        {
          id: "m1-reports",
          title: "Raid the Consulting Firms' Research",
          time: "3–5 hours of reading",
          lesson: [
            "Hedge funds and giant companies spend millions a year identifying market trends because the right trend, spotted early, is worth billions. You get the same intelligence <b>free</b>.",
            "Consulting firms — <b>McKinsey, BCG, Bain</b> and dozens of others — employ armies of analysts to find the biggest market disruptions, then publish the findings as free reports and white papers (it's lead generation for their million-dollar consulting contracts).",
            "Instead of doing the research yourself, leverage their hundreds of thousands of analysts. Read the reports in industries you know or care about.",
          ],
          actions: [
            "Bookmark the insights pages: mckinsey.com/featured-insights, bcg.com/publications, bain.com/insights.",
            "Pick 2–3 industries you have any edge in (worked in, sold to, obsessed with).",
            "Read 5 reports in those industries this week. For each, note every statistic showing rapid change.",
            "Keep a 'disruption log' note in this step: trend, stat, source, who it affects.",
          ],
          metric: "5 reports read, 10+ change-stats logged",
        },
        {
          id: "m2-signals",
          title: "Spot the Three Signals",
          time: "1 week of analysis",
          lesson: [
            "As you read, hunt for exactly three things:",
            "<b>1. A change creating new opportunity.</b> Example from the creator's startup: the share of people wanting to buy cars online jumped from 35% → 48% in one year.",
            "<b>2. A gap in existing solutions.</b> Quick Googling showed car dealerships literally could not sell online. Change + no solution = desperate market.",
            "<b>3. A market big enough.</b> In a small market you must dominate to make good money. In a huge market, a small slice makes you more money than you know what to do with. (Next step gives you the exact math.)",
          ],
          actions: [
            "From your disruption log, shortlist 3 trends with the steepest change.",
            "For each: spend 30 minutes Googling who currently solves this. Write down the gap you find (or cross it off).",
            "For each surviving idea, write the one-line opportunity: 'Because [change], [customer] desperately needs [solution], and nothing serves them.'",
          ],
          metric: "1–3 written opportunity statements",
        },
        {
          id: "m3-math",
          title: "The Billion-Dollar Math Check",
          time: "30 minutes per idea",
          widget: "market-calc",
          lesson: [
            "The formula: <b>(number of customers who would buy) × (price you could charge per year) must exceed $1,000,000,000.</b>",
            "The creator's exact math: Google says there are 48,133 US car dealerships. Dealerships pay $2,000–$5,000/month for software — call it $3,000/month = $36,000/year. 48,133 × $36,000 = <b>$1.7B</b>. Pass. That's the identical calculation behind the business he sold for $110M.",
            "Run your ideas through the calculator below. If an idea fails the check, don't rationalize — go back to the reports.",
          ],
          actions: [
            "Google the number of potential customers for each opportunity (count of businesses/people).",
            "Google what they currently pay for adjacent solutions to anchor your annual price.",
            "Run the calculator on each idea. Kill anything under $1B total market.",
            "Declare your market: write the winning opportunity statement in this step's notes.",
          ],
          metric: "One market that passes the $1B check",
        },
      ],
    },
    {
      id: "p3",
      num: 3,
      title: "Design a High-Leverage Business",
      tagline: "The right idea with the wrong model still fails. Build for 10x revenue multiples, not trading time for money.",
      intro: "At 21 the creator charged $300/hour at his agency and was still a slave to his time — he'd traded a 9-to-5 for a 24/7. In a low-leverage business, $100k of sales minus $50k of costs grows your net worth $50k. In a high-leverage business, the same $100k of revenue can add $1M+ to your net worth (a 10x revenue multiple — Shopify trades at ~29x; Adobe offered ~50x for Figma).",
      steps: [
        {
          id: "l1-tests",
          title: "Pass the Four Leverage Tests",
          time: "1 hour of honest scoring",
          widget: "leverage-score",
          lesson: [
            "<b>1. Recurring revenue.</b> Sell once, get paid repeatedly. Whatever you sell — toothbrushes or software — customers should use it monthly and buy repeatedly. There's a reason everything is becoming a subscription.",
            "<b>2. 70%+ gross margins.</b> If you charge $100/month, it must cost under $30/month to serve. Digital products (software, community, course) get there naturally.",
            "<b>3. Scales through technology, not people.</b> If every new customer requires new headcount, you'll drown in management and never be very profitable. That rules out agencies, consulting, and physical products — they work, but they're messy; avoid them.",
            "<b>4. Your own product.</b> No affiliate marketing, no dropshipping. If you don't own it, terms change under you and any slick marketer can start a pricing war. (Hiring someone to build it is fine — but you must own what's sold.)",
          ],
          actions: [
            "Score your business idea on the scorecard below — all four must pass.",
            "If a test fails, redesign the model (e.g., productize the service, add a subscription) rather than abandoning the market.",
            "Write your final model in one line: 'We charge [customer] $X/month for [product we own] that runs on software.'",
          ],
          metric: "4/4 on the leverage scorecard",
        },
        {
          id: "l2-whw",
          title: "The What → How → Who Framework",
          time: "learn once, use forever",
          lesson: [
            "The creator called hundreds of prospects who loved the idea but didn't buy. Listening back to recorded calls revealed he was selling wrong. The fix sells anything to anyone:",
            "<b>WHAT:</b> figure out what the buyer wants — the change in their life, not your features. In marketing copy, call out that change.",
            "<b>HOW:</b> show how you'll deliver the change — your technology, your method, your specific benefits. If they don't believe your how solves their what, no sale.",
            "<b>WHO:</b> the most-skipped, most-important step. They believe the what and how — now they must believe <i>you</i> can deliver. Pricing, testimonials, reviews, credentials, service commitments. The moment the creator added 'who we are' slides to his deck, people started buying.",
          ],
          actions: [
            "Write your WHAT: the life/business change your buyer gets, in their words (steal phrasing from your interviews).",
            "Write your HOW: the 2–3 specific things that make the change believable.",
            "Build your WHO: collect every credential, story, and proof point you have. No testimonials yet? Line up your first pilot users to get them (Phase 4 shows how).",
            "Record your next 5 pitches and score each against What → How → Who. Fix the weakest section.",
          ],
          metric: "A one-page What/How/Who pitch document",
        },
        {
          id: "l3-loop",
          title: "The Lean Learning Loop",
          time: "run continuously",
          lesson: [
            "Never bet months of your life on an untested guess. The Lean Learning Loop (Lean Startup principles + first-principles thinking) de-risks every move:",
            "<b>1. Hypothesis:</b> write your idea as a testable claim ('If I write a book, my blog readers will buy it').",
            "<b>2. Leanest possible test:</b> don't write the book — add a 'Buy my book' page that collects emails. One hour of work.",
            "<b>3. Collect data & conclude:</b> 30,000 visits → 3,000 clicks → benchmark 10% buy-rate → ~600 books/month × $20 = $12,000/month. NOW write the book — the risk is gone.",
            "Every feature, channel, and pricing idea goes through this loop. It's how you make progress fast without wasting your life on the wrong thing.",
          ],
          actions: [
            "Write your top 3 hypotheses about your business as 'If [action], then [measurable result]' statements.",
            "For each, design the cheapest test that could validate it (landing page, 10 DMs, a pre-order link).",
            "Launch one test this week. Set the success threshold BEFORE you look at results.",
            "Log the result in this step's notes and either double down or kill it. Repeat weekly.",
          ],
          metric: "1+ lean test launched per week",
        },
      ],
    },
    {
      id: "p4",
      num: 4,
      title: "Launch — Sell Before You Build",
      tagline: "The creator sold $500k of product before building it. Build the product first and you're playing the fastest way to fail.",
      intro: "Most entrepreneurs think step one is building the product — no product, no sales, right? Wrong: it's the worst thing you can do. Sell first. When you finally build, you'll have paying customers before risking a dollar. The vehicle is a Customer Advisory Board (CAB), which flips sales resistance on its head.",
      steps: [
        {
          id: "c1-outreach",
          title: "Ask for Advice, Not Orders",
          time: "50 contacts/day",
          lesson: [
            "Build a list of ideal customers and reach out to at least 50 per day — but <b>don't sell</b>. Ask for help. People who'd refuse a sales call will happily give advice.",
            "The script: <i>\"Hey — I'm an entrepreneur building solutions for people like you, and I'd love a brief conversation about your work so I make sure I'm building the best product possible. Would you be open to a quick chat sometime?\"</i>",
            "On the call, genuinely interview them — it's business gold, not a sales trick. Ask about their problems, and whether what you're building would solve them.",
          ],
          actions: [
            "Build a list of 250 ideal customers with contact info (5 days × 50).",
            "Send 50 advice-request messages per day using the script (email, LinkedIn, phone — wherever they live).",
            "Book and run advice interviews; take notes on exact problem language.",
            "After each interview, log: problems, current tools, what they'd pay, and objections you heard.",
          ],
          metric: "50 outreaches/day; interviews booked",
        },
        {
          id: "c2-cab",
          title: "Invite Them to the Customer Advisory Board",
          time: "end of each interview",
          lesson: [
            "When the advice is flowing, make the ask: <i>\"This was so valuable — I'd love to continue these conversations. We're creating a <b>Customer Advisory Board</b>. Would you be interested in joining?\"</i> Giving it an official name raises its perceived status.",
            "Then the exact pitch: <i>\"We're putting together a small group of innovative industry leaders to guide our product development. As a CAB member you get direct access to our team and a voice in the roadmap — so we build the best product for you. To do that you need to actually be using the product, so members get a <b>lifetime 50–70% discount</b>. In return, we ask that you use it, give honest feedback, and let us use your success as a reference.\"</i>",
            "Close with paperwork (official!): <i>\"This isn't a binding purchase — just an LOI, a letter of interest, that reserves your spot on the CAB and tells us you're serious.\"</i>",
          ],
          actions: [
            "Write your own CAB pitch using the template above (pick your discount — 70% works).",
            "Draft a one-page LOI (what members get, what you ask, non-binding language).",
            "Pitch the CAB at the end of every advice interview this week.",
            "Track LOIs signed. Target: 10 before you build anything.",
          ],
          metric: "10 signed LOIs",
        },
        {
          id: "c3-first-revenue",
          title: "Convert the CAB to First Revenue",
          time: "as the product ships",
          lesson: [
            "Your 10 CAB members are pre-sold customers: they've told you their problems, shaped the roadmap, and committed at a lifetime-discount price. When the first version ships, they convert from LOI to paying — and their success stories become the WHO in your What→How→Who pitch for full-price customers.",
            "This is the moment 'significant revenue' starts: 10 customers at even a discounted $100–$1,000/month is your first recurring revenue base, and the reference engine for everything after.",
          ],
          actions: [
            "Set your CAB pricing (discounted from your target list price) and payment method (Stripe invoice is fine).",
            "Convert each LOI to a paid subscription as soon as the product delivers its core promise.",
            "Collect a testimonial and permission to use each member's success as a reference.",
            "Raise to full list price for customer #11 onward.",
          ],
          metric: "10 paying customers; first MRR",
        },
      ],
    },
    {
      id: "p5",
      num: 5,
      title: "Build — The Black Car Product",
      tagline: "\"Any color he wants, so long as it is black.\" One tool, one problem — until it sells repeatedly.",
      intro: "42% of startups die from building the wrong product — even with paying customers. The killer instinct is building an impressive product that wows at every level: it slows development, burns money, and kills companies. Do the opposite.",
      steps: [
        {
          id: "b1-scope",
          title: "Scope It Like Henry Ford",
          time: "ruthless and ongoing",
          lesson: [
            "Your first product should be a <b>black car product</b>: so narrowly scoped it's a singular tool solving one problem, and one problem only — the top-ranked problem from your interviews.",
            "Until you have sold that product and solved that problem <i>repeatedly</i>, you do not build additional features to solve additional problems. Every 'wouldn't it be cool if' goes in a parking-lot list, not the roadmap.",
          ],
          actions: [
            "Write the one-sentence product spec: 'It takes [input] and delivers [the #1 outcome customers asked for]. Nothing else.'",
            "List every feature idea you have, then move all but the core into a 'later' list.",
            "Ship the narrow version to your CAB. Fix only what blocks the core promise.",
            "Only add feature #2 after the core is bought and used repeatedly.",
          ],
          metric: "Core product shipped to CAB; zero scope creep",
        },
        {
          id: "b2-squad",
          title: "Keep a Pizza Squad",
          time: "until $1M in sales",
          lesson: [
            "Beginners think more people = faster progress. Experienced founders know more people = more management overhead and more people problems, grinding you to a halt while you fight fires.",
            "Use Bezos's two-pizza rule: no team bigger than two pizzas can feed — roughly <b>5–8 people</b>. Stay under 8 until you pass $1M in sales. Lean moves fastest.",
          ],
          actions: [
            "List the 2–3 roles you genuinely cannot cover with your skill stack (often: engineering).",
            "Hire contractors/first hires only for those gaps — stay under 8 total.",
            "Before every hire, ask: could a playbook, a tool, or AI do this instead?",
          ],
          metric: "Team ≤ 8 until $1M in sales",
        },
      ],
    },
    {
      id: "p6",
      num: 6,
      title: "Scale — Grow Yourself, Then Free Yourself",
      tagline: "Sequoia fires 45% of founding CEOs within 18 months. The bottleneck at this stage is you.",
      intro: "Early-stage companies double or triple revenue yearly — which means the CEO must grow their own skills 200–300% a year or become the choke point (that's why even Sequoia-backed founders get fired). Make leveling up automatic, find what's working, and turn it into systems that run without you.",
      steps: [
        {
          id: "g1-triad",
          title: "Build Your Triad of Influence",
          time: "assemble over 60 days",
          lesson: [
            "<b>Peers (get 5):</b> people at your level who inspire you and learn alongside you. Find them in meetups, peer groups, conferences, co-work sessions.",
            "<b>Mentors (get 3):</b> a few years ahead of you; they help you dodge potholes and are your panic button. Crucially, NOT your investors — you want unbiased advice. Best found via referrals from peers; grab coffee monthly with progress updates.",
            "<b>Heroes (consume their content):</b> people living your dream life. Don't cold-email them early — the gap is too big. Get their knowledge from their books: <i>The Hard Thing About Hard Things</i> (Ben Horowitz), <i>Shoe Dog</i> (Phil Knight), <i>Total Recall</i> (Arnold Schwarzenegger).",
          ],
          actions: [
            "Join one community (meetup, mastermind, or online group) in your market this week.",
            "List 5 peer candidates and set up recurring co-work or check-in sessions.",
            "Ask your peers for 3 mentor referrals; book the first monthly coffee.",
            "Start the first hero book; queue the other two.",
          ],
          metric: "5 peers + 3 mentors meeting regularly + 3 books queued",
        },
        {
          id: "g2-doubledown",
          title: "Double Down on What Sticks",
          time: "quarterly review",
          lesson: [
            "Early on you throw lots of things at the wall. The trap is staring at what <i>didn't</i> stick and asking 'how do we fix it?' — rational, and the fastest way to fail.",
            "Instead, study what IS working: Are certain company sizes buying more? Does one email sequence convert better? Which channel produced every big win? Those patterns are your <b>superpowers</b> — pour resources into them and starve everything else.",
          ],
          actions: [
            "List everything you tried last quarter (channels, pitches, segments, offers).",
            "Mark the top 20% by revenue produced. Write WHY each worked.",
            "Kill or pause the bottom 50%. Reallocate that time/money to the winners.",
            "Repeat this review every quarter (set a goal with a date in the Goals tab).",
          ],
          metric: "A written 'superpowers' list, refreshed quarterly",
        },
        {
          id: "g3-delegate",
          title: "Document & Delegate",
          time: "the freedom engine",
          lesson: [
            "Scale your superpowers so they run on autopilot without you, via <b>document → delegate</b>:",
            "<b>Document:</b> turn the highest-performing activities into playbooks anyone can follow — record the activity being done, then write steps so carefully that any skill level could execute. Your best closer writes the closing playbook (not you).",
            "<b>Delegate:</b> hire or promote your best people to department leads; they hire, train, and manage others to run the playbooks. Keep the Lean Learning Loop running inside each playbook — test, improve, update.",
            "Result: a multi-million dollar business cranking away with little of your time — freedom and happiness, which was the point all along.",
          ],
          actions: [
            "Identify your top 3 revenue-producing activities.",
            "Have the best person at each record themselves doing it and write the playbook.",
            "Promote/hire a lead per area to own execution and improvement of the playbook.",
            "Block one day a week that is 100% yours — if the business can't survive it, find the missing playbook.",
          ],
          metric: "3 playbooks live, 3 owners running them",
        },
      ],
    },
  ],
  library: [
    { skill: "Money Foundation", name: "Baby Steps Millionaires", author: "Dave Ramsey", why: "The study of 10,167 millionaires behind the 7 Baby Steps — how ordinary incomes become 7-figure net worths." },
    { skill: "Sales & Persuasion", name: "Never Split the Difference", author: "Chris Voss", why: "Stay calm, persuade, and win high-stakes conversations — the tactics behind the $110M exit negotiation." },
    { skill: "Copywriting", name: "Copywriting Secrets", author: "Jim Edwards", why: "Straightforward, modern; teaches the Hook → Persuade → CTA formula that all advertising runs on." },
    { skill: "Product Thinking", name: "The Lean Startup", author: "Eric Ries", why: "The framework for interviewing customers so they teach you exactly what to build." },
    { skill: "Cold Outbound", name: "The Sales Development Playbook", author: "Trish Bertuzzi", why: "A copy-paste outbound system: sequences, cadence, scripts." },
    { skill: "Hero: Operating", name: "The Hard Thing About Hard Things", author: "Ben Horowitz", why: "What running a company is actually like when it's hard." },
    { skill: "Hero: Grit", name: "Shoe Dog", author: "Phil Knight", why: "Nike's founding story — endurance through decades of near-death moments." },
    { skill: "Hero: Ambition", name: "Total Recall", author: "Arnold Schwarzenegger", why: "Reinvention and relentless goal-setting from a self-made billionaire." },
  ],
  reportSources: [
    { name: "McKinsey Featured Insights", url: "https://www.mckinsey.com/featured-insights" },
    { name: "BCG Publications", url: "https://www.bcg.com/publications" },
    { name: "Bain Insights", url: "https://www.bain.com/insights/" },
    { name: "Deloitte Insights", url: "https://www2.deloitte.com/insights" },
    { name: "PwC Research & Insights", url: "https://www.pwc.com/gx/en/research-insights.html" },
    { name: "CB Insights Research", url: "https://www.cbinsights.com/research/" },
  ],
};
